"""add sections and notebook position

Revision ID: ab80aa267c60
Revises: 38698e503e77
Create Date: 2026-09-03 18:37:06.752888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab80aa267c60'
down_revision: Union[str, Sequence[str], None] = '38698e503e77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('position >= 0', name='ck_sections_position_non_negative'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sections_owner_id'), 'sections', ['owner_id'], unique=False)
    op.create_index('ix_sections_owner_id_position', 'sections', ['owner_id', 'position'], unique=False)
    op.create_index('uq_sections_owner_id_lower_title', 'sections', ['owner_id', sa.literal_column('lower(title)')], unique=True)
    op.add_column('notebooks', sa.Column('section_id', sa.UUID(), nullable=True))
    op.add_column('notebooks', sa.Column('position', sa.Integer(), server_default='0', nullable=False))
    op.create_index('ix_notebooks_owner_id_section_id_position', 'notebooks', ['owner_id', 'section_id', 'position'], unique=False)
    op.create_index(op.f('ix_notebooks_section_id'), 'notebooks', ['section_id'], unique=False)
    op.create_foreign_key(None, 'notebooks', 'sections', ['section_id'], ['id'], ondelete='SET NULL')
    op.create_check_constraint('ck_notebooks_position_non_negative', 'notebooks', 'position >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_notebooks_position_non_negative', 'notebooks', type_='check')
    op.drop_constraint(None, 'notebooks', type_='foreignkey')
    op.drop_index(op.f('ix_notebooks_section_id'), table_name='notebooks')
    op.drop_index('ix_notebooks_owner_id_section_id_position', table_name='notebooks')
    op.drop_column('notebooks', 'position')
    op.drop_column('notebooks', 'section_id')
    op.drop_index('uq_sections_owner_id_lower_title', table_name='sections')
    op.drop_index('ix_sections_owner_id_position', table_name='sections')
    op.drop_index(op.f('ix_sections_owner_id'), table_name='sections')
    op.drop_table('sections')
    # ### end Alembic commands ###
